// AXIOS
import axios from 'acios'

// -- *** -- START CODE -- *** -- // 
// -- *** -- START CODE -- *** -- // 

// CREATE ACTION TYPES
    export const CLICK_OBJECTIVE_NEGATIVE_START = 'CLICK_OBJECTIVE_NEGATIVE_START' 
    export const CLICK_OBJECTIVE_NEGATIVE_SUCCESS = 'CLICK_OBJECTIVE_NEGATIVE_SUCCESS' 
    export const CLICK_OBJECTIVE_NEGATIVE_FAILURE = 'CLICK_OBJECTIVE_NEGATIVE_FAILURE' 

    // ACTION CREATOR